'use client'

import Image from "next/image";
import { Bungee } from "next/font/google";
import { PlayIcon } from "./components/Icon";

import logoPic from "@assets/img/logo.png";
import { useState } from "react";
import UserForm from "./components/UserForm";


// export const metadata: Metadata = {
//   title: "Virtual Laboratory: Kinematika Gerak Lurus",
//   description: "Generated by create next app",
// };

const bungee = Bungee({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
});

export default function Home() {
  const [showModal, setShowModal] = useState<boolean>(false);

  const handleOpenModal = () => {
    setShowModal(true)
  }

  const handleCloseModal = () => {
    setShowModal(false)
  }

  return (
    <section className="bg-[url('/assets/img/bg.png')] bg-cover bg-no-repeat h-[100vh] flex flex-col items-center p-60">
      <div className="mb-6">
        <Image
          src={logoPic}
          alt="logo"
          height={86}
        />
      </div>
      <div className={`${bungee.className} text-5xl text-center text-purple-800 mb-16 mx-4 drop-shadow-lg`}>
        <h1 className="mb-6 text-white">Selamat Datang</h1>
        <h2>Virtual Laboratory:</h2>
        <h2>Kinematika Gerak Lurus</h2>
      </div>
      <div className="bg-white/50 p-5 rounded-full pl-6 cursor-pointer" onClick={handleOpenModal}>
        <PlayIcon color="fill-blue-500" width={66} height={66} />
      </div>
      <div className={`${bungee.className} mt-28 text-xl text-center text-yellow-300`}>
        <h6>Nurhasanah</h6>
        <h6>21326251034</h6>
      </div>

      {showModal && (<UserForm handleCloseModal={handleCloseModal} />)}
    </section>
  );
}
